name: Mirror GitHub repo to AWS CodeCommit

on: [push, delete]

jobs:
  to_codecommit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Mirror Action
    env:
      CODECOMMIT_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      CODECOMMIT_SSH_PRIVATE_KEY_ID: ${{ secrets.SSH_PRIVATE_KEY_ID }}
      INPUT_TARGET_REPO_URL: ssh://git-codecommit.ap-southeast-2.amazonaws.com/v1/repos/cc-repo
    run: |
      git --version
      mkdir -p /home/runner/.ssh
      echo "$CODECOMMIT_SSH_PRIVATE_KEY" > /home/runner/.ssh/id_rsa
      cat /home/runner/.ssh/id_rsa
      chmod 600 /home/runner/.ssh/id_rsa
      echo 'Host git-codecommit.ap-southeast-2.amazonaws.com \n  User "$CODECOMMIT_SSH_PRIVATE_KEY_ID" \n  IdentityFile /home/runner/.ssh/id_rsa' > /home/runner/.ssh/config
      export GIT_SSH_COMMAND="ssh -v -i /home/runner/.ssh/id_rsa -o StrictHostKeyChecking=no -l $CODECOMMIT_SSH_PRIVATE_KEY_ID"
      export GIT_TRACE_PACKET=1 && export GIT_TRACE=1 && export GIT_CURL_VERBOSE=1
      chmod 600 /home/runner/.ssh/config
      git remote add mirror "$INPUT_TARGET_REPO_URL"
      git push --tags --force --prune mirror "refs/remotes/origin/*:refs/heads/*"
