name: Mirroring

on: [push]

jobs:
  codecommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pushes to CodeCommit
        env:
          CODECOMMIT_URL: ssh://git-codecommit.ap-southeast-2.amazonaws.com/v1/repos/cc-repo
          HOST_KEY: ${{ secrets.HOST_KEY }}
          SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir .ssh && cd .ssh && echo "$SSH_PRIVATE_KEY" > aws-southeast-2 && chmod 600 aws-southeast-2
          echo "$SSH_CONFIG" > config && chmod 600 config
          git remote add codecommit "$CODECOMMIT_URL"
          git push codecommit --all
