name: Mirroring

on: [push, delete]

jobs:
  to_codecommit:                               
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          https://git-codecommit.ap-southeast-2.amazonaws.com/v1/repos/cc-repo
